server.port: 8080

spring.jpa:
  hibernate.ddl-auto: none
  properties.hibernate.format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: true

logging.level.org.springframework:
  orm.jpa: INFO
  transaction: INFO
  transaction.interceptor: TRACE
  orm.jpa.JpaTransactionManager: DEBUG
  boot.autoconfigure.jdb: DEBUG

logging.level.org.hibernate:
  SQL: DEBUG
  type: TRACE
  jdbc.bind: TRACE

spring.datasource:
  initialization-mode: always
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://ewm-db:5432/ewm
  username: ewm
  password: 12345

logging.level.ru.practicum.emw: DEBUG




