server.port: 9090

spring.jpa:
  hibernate.ddl-auto: none
  properties.hibernate.format_sql: true
spring.sql.init:
      mode: always
      schema-locations: classpath:schema.sql

logging.level.org.springframework:
  orm.jpa: INFO
  transaction: INFO
  transaction.interceptor: TRACE
  orm.jpa.JpaTransactionManager: DEBUG
  boot.autoconfigure.jdb: DEBUG

logging.level.org.hibernate:
  SQL: DEBUG
  jdbc.bind: TRACE

spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://stats-db:5432/stats
  username: stats
  password: 12345

logging.level.ru.practicum.emw: DEBUG
